# yaml-language-server: $schema=https://taskfile.dev/schema.json
# Author: Ulyses Edcel C. Adrales <ulysesadrales@gmail.com>
version: "3"
env:
  OPEN_WEBUI_DATA: .data
  DEFAULT_INSTRUCT_SRC: https://huggingface.co/unsloth/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-Q4_K_M.gguf
  DEFAULT_INSTRUCT_MODEL: Llama-3.2-3B-Instruct-Q4_K_M
  DEFAULT_INSTRUCT_DIR: models/instruct
  DEFAULT_INSTRUCT_PORT: 8888
  DEFAULT_EMBEDDING_SRC: https://huggingface.co/nomic-ai/nomic-embed-text-v1.5-GGUF/resolve/main/nomic-embed-text-v1.5.f16.gguf
  DEFAULT_EMBEDDING_MODEL: nomic-embed-text-v1.5.f16
  DEFAULT_EMBEDDING_DIR: models/embedding
  DEFAULT_EMBEDDING_PORT: 8008
tasks:
  launch:
    desc: Launch the AI interface server
    deps: [serve-instruct, serve-embedding]
    env:
      DATA_DIR: "{{.OPEN_WEBUI_DATA}}"
      OPENAI_API_BASE_URL: http://localhost:{{.DEFAULT_INSTRUCT_PORT}}/v1
      DEFAULT_MODELS: "{{.DEFAULT_INSTRUCT_MODEL}}"
      RAG_EMBEDDING_ENGINE: openai
      RAG_OPENAI_API_BASE_URL: http://localhost:{{.DEFAULT_EMBEDDING_PORT}}/v1
      RAG_EMBEDDING_MODEL: "{{.DEFAULT_EMBEDDING_MODEL}}"
    cmds:
      - task: scaffold
        vars:
          DIR: "{{.OPEN_WEBUI_DATA}}"
      - defer: {task: clean-up}
      - uvx --python 3.11 open-webui serve
  scaffold:
    desc: Create directory unless existing
    internal: true
    status:
      - fd --type d {{.DIR}} --quiet
    cmd: mkdir -p {{.DIR}}
  dl-default-model:
    desc: Download default GGUF model
    internal: true
    status:
      - fd -q -e gguf . {{.DIR}}
    cmd: aria2c -x16 -s16 -d {{.DIR}} -o {{.FILE}} {{.SRC}}
  serve-instruct:
    desc: Launch llama server for instruct models
    internal: true
    env:
      LLAMA_ARG_PORT: "{{.DEFAULT_INSTRUCT_PORT}}"
      LLAMA_ARG_MODELS_DIR: "{{.DEFAULT_INSTRUCT_DIR}}"
      LLAMA_ARG_TEMPERATURE: 0
      LLAMA_ARG_CTX_SIZE: 4096
      LLAMA_ARG_CACHE_TYPE_K: q8_0
      LLAMA_ARG_CACHE_TYPE_V: q8_0
      LLAMA_ARG_FLASH_ATTN: 1
      LLAMA_ARGS_THREADS: 4
      LLAMA_ARG_TOOLS: all
    cmds:
      - task: scaffold
        vars:
          DIR: $DEFAULT_INSTRUCT_DIR
      - task: dl-default-model
        vars:
          DIR: $DEFAULT_INSTRUCT_DIR
          SRC: $DEFAULT_INSTRUCT_SRC
          FILE: $DEFAULT_INSTRUCT_MODEL.gguf
      - llama-server &
      - task: delay
      - wait4x http http://localhost:{{.DEFAULT_INSTRUCT_PORT}}/health
  serve-embedding:
    desc: Launch llama server for embedding models
    internal: true
    env:
      LLAMA_ARG_PORT: "{{.DEFAULT_EMBEDDING_PORT}}"
      LLAMA_ARG_MODELS_DIR: "{{.DEFAULT_EMBEDDING_DIR}}"
      LLAMA_ARG_EMBEDDINGS: true
    cmds:
      - task: scaffold
        vars:
          DIR: $DEFAULT_EMBEDDING_DIR
      - task: dl-default-model
        vars:
          DIR: $DEFAULT_EMBEDDING_DIR
          SRC: $DEFAULT_EMBEDDING_SRC
          FILE: $DEFAULT_EMBEDDING_MODEL.gguf
      - llama-server &
      - task: delay
      - wait4x http http://localhost:{{.DEFAULT_EMBEDDING_PORT}}/health
  delay:
    desc: Add 3 seconds delay
    internal: true
    cmds:
      - cmd: sleep 3
        platforms: [linux, darwin]
      - cmd: cmd.exe /c "timeout /t 3 /nobreak"
        platforms: [windows]
  clean-up:
    desc: Shutdown all llama servers
    cmds:
      - cmd: pkill -SIGINT -f llama-server || true
        platforms: [linux, darwin]
      - cmd: taskkill /IM "llama-server.exe" /T /F || exit 0
        platforms: [windows]
